name: Build and publish multi-arch container images

on:
  push:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual trigger'
        required: true
        default: ''

jobs:
  ghcr_build_and_push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.inputs.reason != ''

    steps:
      - name: Build Docker image
        run: |
          REPO_OWNER_LOWERCASE=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/InfiniteAICreations/ghcr-demo:latest .

      - name: Log-in to ghcr.io
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push multi-arch container images
        run: |
          docker push ghcr.io/infiniteaicreations/ghcr-demo:latest
